index:
   path: /
   controller: App\Controller\HomeController::index

portfolio_index:
    path: /portfolio
    controller: App\Controller\PortfolioController::index

login:
   path: /login
   controller: App\Controller\LoginController::login

logout:
   path: /logout
   controller: App\Controller\LoginController::logout

dashboard_index:
    path: /dashboard
    controller: App\Controller\DashboardController::index
